server:
  error:
    include-stacktrace: never
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/databases/iot-mas-services
    driver-class-name: org.h2.Driver
    username: 
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: false
